version: '3.8'

services:
  db:
    image: postgres:15
    container_name: lumine_postgres
    restart: always
    environment:
      POSTGRES_DB: lumine_dev
      POSTGRES_USER: lumine_admin
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
