package com.lumine.helpers;

public enum LanguageName {
    // ===== English Variants =====
    ENGLISH,
    AMERICAN_ENGLISH,
    AUSTRALIAN_ENGLISH,
    CANADIAN_ENGLISH,
    BRITISH_ENGLISH,
    IRISH_ENGLISH,
    INDIAN_ENGLISH,
    SOUTH_AFRICAN_ENGLISH,

    // ===== Spanish Variants =====
    SPANISH,
    SPANISH_ARGENTINA,
    SPANISH_BOLIVIA,
    SPANISH_CHILE,
    SPANISH_COLOMBIA,
    SPANISH_COSTA_RICA,
    SPANISH_DOMINICAN_REPUBLIC,
    SPANISH_ECUADOR,
    SPANISH_SPAIN,
    SPANISH_GUATEMALA,
    SPANISH_HONDURAS,
    SPANISH_MEXICO,
    SPANISH_NICARAGUA,
    SPANISH_PANAMA,
    SPANISH_PERU,
    SPANISH_PUERTO_RICO,
    SPANISH_PARAGUAY,
    SPANISH_EL_SALVADOR,
    SPANISH_US,
    SPANISH_URUGUAY,
    SPANISH_VENEZUELA,

    // ===== French Variants =====
    FRENCH,
    FRENCH_BELGIUM,
    FRENCH_CANADA,
    FRENCH_SWITZERLAND,
    FRENCH_FRANCE,
    FRENCH_LUXEMBOURG
}
